### ISSUE TITLE
Getting {TypeError: Cannot read property 'confirmed' of undefined} when i my internet is disconnected.

### ISSUE THREAD

**Issue by itsnoormuhammad** [adrianhajdin/project_corona_tracker#12]
when i disconnect the internet i get this do not know why see here. 
![err](https://user-images.githubusercontent.com/55230083/84064764-a424dd00-a9dc-11ea-9c43-5d20204156a1.PNG)

**Comment by Reetpriye** [comment]
If you can provide me your GitHub repo link. I'll definitely try my best to solve it.

**Comment by itsnoormuhammad** [comment]
https://github.com/itsnoormuhammad/react-corona-app.git

**Comment by Gokulnathnallaiya** [comment]
They have changed the structure of api call(json object). 
make these changes in the App.js file. it will work fine.
![issue image](https://user-images.githubusercontent.com/58301759/85204616-46c15200-b333-11ea-89da-3c6138d580e0.PNG)

**Comment by tejasautkar** [comment]
I am also getting the same error even after making changes.
I got stuck in the middle of the project due to same.

[https://github.com/tejasautkar/covid-react-app.git](https://github.com/tejasautkar/covid-react-app.git)

**Comment by Gokulnathnallaiya** [comment]
I have completed the project but with some modifications. But i used the same api. you can check my repo for reference.

Repo link https://github.com/Gokulnathnallaiya/Covid19--tracker-app

Live site : https://covid-19-pandemic.herukoapp.com

Feel free to give a star if it is usefull

Live site :

**Comment by adrianhajdin** [comment]
The data cannot be fetched from the API if there's no internet connection.
