### ISSUE TITLE
To solution

### ISSUE THREAD

**Issue by Muhammad-Tayyab1** [adrianhajdin/project_corona_tracker#14]
![Screenshot (2)](https://user-images.githubusercontent.com/66192491/85207728-42e9fb80-b344-11ea-84ac-acfc8b376906.png)
 hi sir
 i have face this problem about last three days but i failed to solve this 
please say something about this error

GITHUB id :
https://github.com/Muhammad-Tayyab1

**Comment by Gokulnathnallaiya** [comment]
I have completed the project yesterday(22/06/2020) but, with some modifications. But i used the same api. you can check my repo for reference.

Repo link https://github.com/Gokulnathnallaiya/Covid19--tracker-app

Live site : http://covid-19-pandemic.herokuapp.com/

Feel free to give a star if it is usefull

**Comment by chiragobhan** [comment]
Hi @Muhammad-Tayyab1, according to your screenshot, you don't seem to have an internet connection. Without any internet connection, the application will not be able to make any API calls to the remote server.
