### ISSUE TITLE
dailyData returned empty array 

### ISSUE THREAD

**Issue by isakulaksiz** [adrianhajdin/project_corona_tracker#21]
[Chart.jsx](https://github.com/isakulaksiz/corona-tracker/blob/master/src/components/Chart/Chart.jsx)
```
import React, {useState, useEffect} from 'react';
import { fetchDailyData } from '../../api';
import { Line, Bar } from 'react-chartjs-2';
import styles from './Chart.module.css';
```
`
const Chart = () => {
    const [dailyData, setDailyData] = useState([]);
  
    useEffect(() => {
        const fetchApi = async () => {
            setDailyData(await fetchDailyData());
        }

        fetchApi();
    });

    console.log("dailyData: ", dailyData);

    const lineChart = (
        dailyData.length
        ?  (   
            <Line  data={{
            labels: dailyData.map(({date}) => date), 
            datasets: [{
                data: dailyData.map(({ confirmed }) => confirmed),
                label: 'Infected',
                borderColor: '#3333fff',
                fill: true,
            },{
                data: dailyData.map(({ deaths }) => deaths),
                label: 'Deaths',
                borderColor: 'red',
                backgroundColor: 'rgba(255, 0, 0, 0.5)',
                fill: true,
            }]
        }} />) : null

    );

    return(
       <div className={ styles.container }>
           {lineChart}
       </div>
    )
}

export default Chart;
`

![sss](https://user-images.githubusercontent.com/26628508/94551312-d5603c00-025d-11eb-91ad-5fd93f0b4e39.JPG)

**Comment by sanchit-mishra** [comment]
I would like to work on this issue

**Comment by sanchit-mishra** [comment]
I checked it out and since it's giving Bad Gateway Error (Code: 502), it's mainly due to because one of the edge server is giving you invalid response that is no data and this is the reason the dailyData return an empty array because actually it is not getting any response from that api request.

**Comment by zpreston123** [comment]
This is an issue related to the API:  https://github.com/mathdroid/covid-19-api/issues/303
