### ISSUE TITLE
Problem when displaying the charts

### ISSUE THREAD

**Issue by RobyCigar** [adrianhajdin/project_corona_tracker#25]
![image](https://user-images.githubusercontent.com/69680330/97983331-ba0dc100-1e07-11eb-95be-a736fe507b8b.png)
Anyone know why my chart like this? I want to make the latest data on the right side.
Thank you.

**Comment by jayden-leuciuc** [comment]
I have the same question, glad it happened to other people, because this was frustrating.

**Comment by 08fdange** [comment]
It’s because the new API used for global daily data has the dates in descending order. Use the javascript array method “reverse()” on the dailyData before mapping the dates for the labels to solve this.

**Comment by RobyCigar** [comment]
thank you @08fdange
