### ISSUE TITLE
Api Not updating recovered data

### ISSUE THREAD

**Issue by jatin711-debug** [adrianhajdin/project_corona_tracker#36]
Not Updating recovered data, error in Api itself

**Comment by avinash201199** [comment]
> Not Updating recovered data, error in Api itself

how to correct this ? any modification you have done ?please reply
@jatin711-debug

**Comment by jatin711-debug** [comment]
Instead of using api used in project use this api-> https://rapidapi.com/Gramzivi/api/covid-19-data/  Just make sure you Destructure data accordingly

**Comment by avinash201199** [comment]
> Instead of using api used in project use this api-> https://rapidapi.com/Gramzivi/api/covid-19-data/ Just make sure you Destructure data accordingly

Thank you so much
