### ISSUE TITLE
Invalid Date Found

### ISSUE THREAD

**Issue by AWAIS97** [adrianhajdin/project_corona_tracker#6]
Hi, I am getting **invalid date** on cards and also I found **undefine** in date buttom of line chart and also when i hover on the line chart.
That i am missing?

**Comment by Reetpriye** [comment]
{new Date(lastUpdate).toDateString()}
Try adding this.

**Comment by AWAIS97** [comment]
I already trried this but this give **Invalid Date**.

**Comment by Reetpriye** [comment]
Can you share the link of your repository. I'll check and comment back.

**Comment by AWAIS97** [comment]
https://github.com/AWAIS97/Covid-19site.git

**Comment by Reetpriye** [comment]
Just a small thing you missed.
It's lastUpdate "capital letter U"
You typed small letter everywhere while de-structuring.
Check that.
I hope everything'll fine after this.

**Comment by AWAIS97** [comment]
Ok I got it.
But still **undefine** in line chart at buttom and in hover.

**Comment by shaikhreza43** [comment]
Yeah, Same issue here as well. You can fix it by using today's date. i.e {new Date(Date.now()).toDateString()}

**Comment by shaikhreza43** [comment]
Make sure the variable is lastUpdate not lastUpdated. Check in Api and index,js. You migh be using lastUpdated... It worked and solved my issue

**Comment by AWAIS97** [comment]
ok bro
 thanks for sharing
